# -*- coding: utf-8 -*-
"""Random Walk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ps7O_ca1F0o-Y_L5svte20lBLapkUye0

Simulasi Gerak Random Walk

1.1D dengan 2 kemungkinan pergerakan

2.1D dengan 3 kemungkinan pergerakan

3.gerak partikel 2D diskrit dengan 5 kemugkinan arah pergerakan

4.gerak partikel 2D dengan kemungkinan pergerakan berdistribusi normal.

5.(Xi+-1, yi+1) = (xi, vi)+c, dengan e € {(0, -1), (0, 1), (0, 0), (-1, 0), (1, 0)}

6.(Xi+1, Vi+1) = (xi, yi) + (Ex, Ey), dengan 6x, Ey ~ N(0,1)
"""

import matplotlib.pyplot as plt
import random
import numpy as np

#2 Kemungkinan arah pergerakan
pos = [0, 0]

positions = [pos.copy()]

for i in range(100):
    direction = random.choice(["E", "W"])

    if direction == "E":
        pos[0] += 1
    elif direction == "W":
        pos[0] -= 1

    positions.append(pos.copy())

positions = np.array(positions)

# Buat plot
plt.plot(positions[:, 0], positions[:, 1])
plt.show()

# print(positions)

#3 kemungkinan arah pergerakan
pos = [0, 0]

positions = [pos.copy()]

for i in range(100):
    direction = random.choice(["E", "W","N"])

    if direction == "E":
        pos[0] += 1
    elif direction == "W":
        pos[0] -= 1
    elif direction == "N":
        pos[1] += 1

    positions.append(pos.copy())

positions = np.array(positions)

plt.plot(positions[:, 0], positions[:, 1])
plt.show()

# print(positions)

#4 kemungkinan
pos = [0, 0]

positions = [pos.copy()]
for i in range(100):
    direction = random.choice(["N", "S", "E", "W"])

    if direction == "N":
        pos[1] += 1
    elif direction == "S":
        pos[1] -= 1
    elif direction == "E":
        pos[0] += 1
    elif direction == "W":
        pos[0] -= 1
    positions.append(pos.copy())

positions = np.array(positions)

plt.plot(positions[:, 0], positions[:, 1])
plt.show()
# print(positions)

#5 kemungkinan
pos = [0, 0]

positions = [pos.copy()]

for i in range(100):
    direction = random.choice(["N", "SE", "E", "W","SW"])

    if direction == "N":
        pos[1] += 1
    elif direction == "SE":
        pos[1] -= 1
        pos[0] += 1
    elif direction == "E":
        pos[0] += 1
    elif direction == "W":
        pos[0] -= 1
    elif direction == "SW":
        pos[1] -= 1
        pos[0] -= 1

    positions.append(pos.copy())

positions = np.array(positions)

plt.plot(positions[:, 0], positions[:, 1])
plt.show()
# print(positions)

#2 
import matplotlib.pyplot as plt
import random
x = 0
y = 0
epsilon = 1
x_positions = []
y_positions = []
langkah = 100

for i in range (langkah):
    ex = random.gauss(0, 1)
    ey = random.gauss(0, 1)
    
    x += epsilon * ex
    y += epsilon * ey
    x_positions.append(x)
    y_positions.append(y)
    
plt.plot(x_positions, y_positions)
plt.show()
# print(positions)